language: node_js
node_js:
  # Disable v12 until tiny-secp256k1 is fixed
  # https://github.com/bitcoinjs/tiny-secp256k1/issues/38
  # - '12'
  - '10'
  - '8'
script: npm test && npm run bench
after_success: npm run coverage
notifications:
  email:
    on_success: never
